### ISSUE TITLE
Packing unoptimized FParsecCS?

### ISSUE THREAD

**Issue by NinoFloris** [stephan-tolksdorf/fparsec#26] opened 2018-03-05 00:38 UTC
BenchmarkDotNet does a verification of all dependencies to see if they have been built with optimizations on. It states fparsec cs isn't, fparsec itself is alright according to BDN (1.0.3 and 1.0.4-rc tested)

```
// Validating benchmarks:
Assembly PerformanceTests which defines benchmarks references non-optimized FParsecCS
```

https://github.com/dotnet/BenchmarkDotNet/

**Comment by stephan-tolksdorf** [comment] 2018-03-05 12:10
Seems like I overlooked that when transitioning to the new project files. Thanks for reporting this issue!

Could you please check whether the issue is fixed in the new 1.0.4-RC2 package I just pushed?

If you're running a benchmark, I'd be also interested in whether you can measure a difference when using the 'FParsec-Big-Data-Edition' package instead.

**Comment by NinoFloris** [comment] 2018-03-05 14:42
Yes one part is fixed, however I get package downgrade warnings with 2.0.3 as that sdk target has a dependency on Fsharp Core >= 4.2.0 while 1.0.4-RC2 now forces 4.3.4

**Comment by stephan-tolksdorf** [comment] 2018-03-05 20:23
I'm referencing the `FSharp.Core` with

    <ItemGroup><PackageReference Include="FSharp.Core" Version="4.*" /></ItemGroup>

Apparently that leads to problems? What's the best practice for referencing `FSharp.Core`?

Unfortunately, .NET Core doesn't implement all the APIs that the full FParsec uses and I currently don't have the time to adapt the code.

**Comment by NinoFloris** [comment] 2018-03-05 20:30
Not needed anymore just like referencing fsharp sdk, it's all integrated since 2.0 into Microsoft.NET.Sdk also to prevent problems like these.

https://github.com/dotnet/sdk/pull/1172

**Comment by stephan-tolksdorf** [comment] 2018-03-05 20:40
Thanks! So, should I just delete this line https://github.com/stephan-tolksdorf/fparsec/blob/master/Build/FParsec.Common.targets#L75  or would you suggest other changes too when building for netstandard/netcore? (It's been a while since I last did .NET development.)

**Comment by NinoFloris** [comment] 2018-03-05 21:01
Yes! Together with https://github.com/stephan-tolksdorf/fparsec/blob/master/Build/FParsec.Common.targets#L65

Although do take note that netstandard 1.6 didn't have it pre-packaged yet so you'll have to keep it around for that one.

**Comment by stephan-tolksdorf** [comment] 2018-03-05 21:19
Thanks again!

I use FSharp.Core from FParsecCS too, so it seem I actually need an explicit reference. Do you have a suggestion for what form it should take?

Does the SDK only have relevance at build time, or does it also affect the built packages? I'm fine with requiring the current .NET Core for building FParsec.

**Comment by NinoFloris** [comment] 2018-03-05 21:44
SDK targets define your nuget deps as well so we as consumers will notice changes.   

For netstandard >= 2.0 I'd lowball it right now to 4.2.* so the current stable sdk 2.1.4 won't have any downgrade warnings. You'd do this by adding (this overrides any default range defined by your installed sdk)
`<FSharpCoreImplicitPackageVersion>4.2.*</FSharpCoreImplicitPackageVersion>`

I also see there is an open issue around the fact FSharpCoreImplicitPackageVersion (of a package) has higher priority than the users project, they're working on making FSharp.Core a truly transparent implicit reference, so it only supplies the package constraint if no other downstream one is defined.  
https://github.com/dotnet/core/issues/907

**Comment by stephan-tolksdorf** [comment] 2018-03-05 23:46
Currently I'm only targeting netstandard1.6 (besides the legacy targets). Do you suggest that I should add netstandard2.0 as an additional target? Could I just continue with an older explicit version instead, or would that cause issues too?

**Comment by NinoFloris** [comment] 2018-03-05 23:49
If you're just targeting 1.6 your best bet indeed seems to target something like 4.2.x. That period came paired with a lot of churn, no pretty solutions there.

**Comment by stephan-tolksdorf** [comment] 2018-03-06 10:51
netstandard 1.6 has all the API surface that FParsec currently needs and was (still is?) the recommended target. 

I've just published RC3, with an explicit reference to 4.2.3. Could you please check, whether that works for you?

**Comment by NinoFloris** [comment] 2018-03-07 15:33
Sorry for the silence, have been sick last few days.

Looks all good now! FParsec package refs even get neatly redirected to 4.3.4 (probably an automatic binding redirect on FSharp.Core)

<img width="359" alt="screen shot 2018-03-07 at 16 33 10" src="https://user-images.githubusercontent.com/4218809/37101203-4420eb42-2225-11e8-91b3-3007728bb6bf.png">

**Comment by stephan-tolksdorf** [comment] 2018-03-07 19:12
Thanks again for reporting the optimization issue and for helping me with the Nuget packages! Get well soon!

**Closed by stephan-tolksdorf** 2018-03-07 19:12 UTC
